// <auto-generated />
namespace CarNotes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addrelationbetweenRefuelEventandGasStation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrelationbetweenRefuelEventandGasStation));
        
        string IMigrationMetadata.Id
        {
            get { return "202108232108438_add relation between RefuelEvent and GasStation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
