// <auto-generated />
namespace CarNotes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addexpensestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addexpensestable));
        
        string IMigrationMetadata.Id
        {
            get { return "202202272151189_Add expenses table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
